"""canonical product catalogue and prices

Revision ID: 1957c83283c6
Revises: fd5de3adf153
Create Date: 2026-08-25 21:23:42.229883
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1957c83283c6"
down_revision: str | None = "fd5de3adf153"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "insurance_products",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("insurer_id", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("external_product_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["insurer_id"], ["insurers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insurer_id", "name", name="uq_product_insurer_name"),
    )
    op.create_index("ix_insurance_products_domain", "insurance_products", ["domain"], unique=False)
    op.create_table(
        "product_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("uin_or_reference", sa.String(length=128), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_name", sa.String(length=300), nullable=False),
        sa.Column("source_reference", sa.String(length=300), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_by", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["insurance_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "version_label", name="uq_version_product_label"),
    )
    op.create_index(
        "ix_product_versions_active", "product_versions", ["product_id", "active"], unique=False
    )
    op.create_table(
        "product_facts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_version_id", sa.String(length=64), nullable=False),
        sa.Column("fact_key", sa.String(length=64), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("critical_for_matching", sa.Boolean(), nullable=False),
        sa.Column("source_reference", sa.String(length=300), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_version_id"], ["product_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_version_id", "fact_key", name="uq_fact_version_key"),
    )
    op.create_table(
        "product_prices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_version_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_period", sa.String(length=16), nullable=False),
        sa.Column("taxes_included", sa.Boolean(), nullable=True),
        sa.Column("fees_included", sa.Boolean(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_name", sa.String(length=300), nullable=False),
        sa.Column("source_quote_id", sa.String(length=128), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("underwriting_required", sa.Boolean(), nullable=True),
        sa.Column("assumptions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_version_id"], ["product_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_product_prices_version_status",
        "product_prices",
        ["product_version_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_prices_version_status", table_name="product_prices")
    op.drop_table("product_prices")
    op.drop_table("product_facts")
    op.drop_index("ix_product_versions_active", table_name="product_versions")
    op.drop_table("product_versions")
    op.drop_index("ix_insurance_products_domain", table_name="insurance_products")
    op.drop_table("insurance_products")
    op.drop_table("insurers")
    # ### end Alembic commands ###
