"""recommendation runs and candidates

Revision ID: 1b5eb8fe7814
Revises: dd40c349fe58
Create Date: 2026-08-25 03:11:50.225786
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1b5eb8fe7814"
down_revision: str | None = "dd40c349fe58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("questionnaire_session_id", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("questionnaire_version", sa.String(length=64), nullable=False),
        sa.Column("scoring_version", sa.String(length=64), nullable=False),
        sa.Column("catalogue_version", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("presentation_mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_session_id"], ["questionnaire_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recommendation_runs_user", "recommendation_runs", ["user_id"], unique=False)
    op.create_table(
        "recommendation_candidates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_run_id", sa.String(length=64), nullable=False),
        sa.Column("product_reference", sa.String(length=64), nullable=False),
        sa.Column("eligibility_status", sa.String(length=24), nullable=False),
        sa.Column("presentation_order", sa.Integer(), nullable=False),
        sa.Column("reason_summary_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_run_id"], ["recommendation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendation_candidates_run",
        "recommendation_candidates",
        ["recommendation_run_id", "presentation_order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recommendation_candidates_run", table_name="recommendation_candidates")
    op.drop_table("recommendation_candidates")
    op.drop_index("ix_recommendation_runs_user", table_name="recommendation_runs")
    op.drop_table("recommendation_runs")
    # ### end Alembic commands ###
