"""questionnaire sessions, answers, priority profiles

Revision ID: dd40c349fe58
Revises: 92283f54b346
Create Date: 2026-08-24 23:52:57.612461
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dd40c349fe58"
down_revision: str | None = "92283f54b346"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnaire_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("questionnaire_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_questionnaire_sessions_user_domain",
        "questionnaire_sessions",
        ["user_id", "domain"],
        unique=False,
    )
    op.create_table(
        "priority_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("questionnaire_session_id", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_session_id"], ["questionnaire_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("questionnaire_session_id"),
    )
    op.create_table(
        "questionnaire_answers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=False),
        sa.Column("answer_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["questionnaire_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "question_id", name="uq_answer_session_question"),
    )
    op.create_table(
        "priority_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("priority_profile_id", sa.String(length=64), nullable=False),
        sa.Column("factor_key", sa.String(length=64), nullable=False),
        sa.Column("priority_level", sa.String(length=16), nullable=False),
        sa.Column("rank_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["priority_profile_id"], ["priority_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("priority_profile_id", "factor_key", name="uq_priority_profile_factor"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("priority_items")
    op.drop_table("questionnaire_answers")
    op.drop_table("priority_profiles")
    op.drop_index("ix_questionnaire_sessions_user_domain", table_name="questionnaire_sessions")
    op.drop_table("questionnaire_sessions")
    # ### end Alembic commands ###
